# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://anetakaczynska.github.io/uid3/"

git_url = "https://github.com/anetakaczynska/uid3/tree/master/"

def custom_doc_links(name): return None
